//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPlanv2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class easyPlanEntities : DbContext
    {
        public easyPlanEntities()
            : base("name=easyPlanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Adelantos> Tbl_Adelantos { get; set; }
        public virtual DbSet<Tbl_Clientes> Tbl_Clientes { get; set; }
        public virtual DbSet<Tbl_Historial> Tbl_Historial { get; set; }
        public virtual DbSet<Tbl_Jornada> Tbl_Jornada { get; set; }
        public virtual DbSet<Tbl_Prestamos> Tbl_Prestamos { get; set; }
        public virtual DbSet<Tbl_Salario> Tbl_Salario { get; set; }
        public virtual DbSet<Tbl_Trabajador> Tbl_Trabajador { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
